version: '3.4'

services:
  # SKOOP WebApp
  webapp:
    image: 'skoop/webapp:latest'
    environment:
      SERVER_NAME: '${SERVER_DOMAIN:-localhost}'
      SERVER_ADMIN: '${SERVER_ADMIN:-anonymous@nothing.com}'
      SKOOP_SERVER_URL: 'http://server:8080'
      SKOOP_WEBAPP_AUTHENTICATION_ISSUER: 'http://${SERVER_DOMAIN:-localhost}:9000/auth/realms/MySkills'
      SKOOP_WEBAPP_AUTHENTICATION_INSECURE: 'true'
    ports:
      - '80:80'
    restart: always

  # SKOOP Server
  server:
    image: 'skoop/server:latest'
    environment:
      SPRING_DATA_NEO4J_URI: 'bolt://database:7687'
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: topsecret
      SPRING_DATA_NEO4J_AUTOINDEX: assert
      SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: 'http://keycloak:8080/auth/realms/MySkills/protocol/openid-connect/certs'
    depends_on:
      - database
      - keycloak
    restart: always

  # Neo4j database for SKOOP Server
  database:
    image: 'neo4j:3.4'
    environment:
      NEO4J_AUTH: neo4j/topsecret
    volumes:
      - 'server-data:/data'
    restart: always

  # KeyCloak server for authentication
  keycloak:
    image: 'jboss/keycloak:4.8.3.Final'
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - 'keycloak-data:/opt/jboss/keycloak/standalone/data'
    ports:
      - '9000:8080'
    restart: always

volumes:
  server-data:
  keycloak-data:
