version: '3.4'

services:
  # MySkills WebApp
  webapp:
    image: 'myskills/webapp:latest'
    environment:
      SERVER_NAME: '${SERVER_DOMAIN:-localhost}'
      SERVER_ADMIN: '${SERVER_ADMIN:-anonymous@nothing.com}'
      MYSKILLS_SERVER_URL: 'http://server:8080'
      MYSKILLS_WEBAPP_AUTHENTICATION_ISSUER: 'http://${SERVER_DOMAIN}:9000/auth/realms/MySkills'
      MYSKILLS_WEBAPP_AUTHENTICATION_INSECURE: 'true'
    ports:
      - '80'
    restart: always

  # MySkills Server
  server:
    image: 'myskills/server:latest'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_NEO4J_URI: 'bolt://database:7687'
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: topsecret
      SECURITY_OAUTH2_RESOURCE_JWK_KEYSETURI: 'http://keycloak:8080/auth/realms/MySkills/protocol/openid-connect/certs'
    depends_on:
      - database
      - keycloak
    restart: always

  # Neo4j database for MySkills Server
  database:
    image: 'neo4j:3.4'
    environment:
      NEO4J_AUTH: neo4j/topsecret
    volumes:
      - 'server-data:/data'
    restart: always

  # KeyCloak server for authentication
  keycloak:
    image: 'jboss/keycloak:4.5.0.Final'
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - 'keycloak-data:/opt/jboss/keycloak/standalone/data'
    ports:
      - '9000:8080'
    restart: always

volumes:
  server-data:
  keycloak-data:
